# Stage 1
FROM node:22.20.0 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2
FROM nginx:latest
COPY --from=build /app/dist/todo-fe/browser /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf